version: "2.1"
services:
  plex-recommendations:
    image: silkychap/plex-recommendations-ai:latest
    container_name: plex-recommendations
    environment:
      - PLEX_URL=<local plex url>
      - PLEX_TOKEN=<plex token>
      - OLLAMA_URL=<ollama server url> # Change to use Ollama instead of OpenAI
      - LIBRARY_NAME=<library name>
      - COLLECTION_TITLE=<title>
      - HISTORY_AMOUNT=<amount> # How far it will look into your plex watch history
      - RECOMMENDED_AMOUNT=<amount> # How many recommendations it will request
      - MINIMUM_AMOUNT=<amount> # The minimum amount of matches it will need to create the collection
      - SECONDS_TO_WAIT=<amount> # How long in seconds it will wait to call again (default: 86400)
    restart: unless-stopped
