version: "2.1"
services:
  plex-recommendations:
    build: .
    container_name: plex-recommendations
    env_file:
      - .env  # Load environment variables from the .env file
    restart: unless-stopped
